### ISSUE TITLE
杀毒软件导致卡在‘执行InjectStarter’这一步了

### ISSUE THREAD

**Issue by zwsts** [xjw580/Hearthstone-Script#40]
日志
```
2024-10-15 13:52:27.187 [Launch VThread] [StartupInfoLogger.java:50] INFO  Starting application using Java 21.0.4 with PID 20244 (started by akane in C:\Users\akane\Desktop\sc)
2024-10-15 13:52:27.190 [Launch VThread] [SpringApplication.java:662] INFO  No active profile set, falling back to 1 default profile: "default"
2024-10-15 13:52:28.253 [Launch VThread] [TomcatWebServer.java:109] INFO  Tomcat initialized with port 8848 (http)
2024-10-15 13:52:28.263 [Launch VThread] [DirectJDKLog.java:173] INFO  Initializing ProtocolHandler ["http-nio-8848"]
2024-10-15 13:52:28.265 [Launch VThread] [DirectJDKLog.java:173] INFO  Starting service [Tomcat]
2024-10-15 13:52:28.265 [Launch VThread] [DirectJDKLog.java:173] INFO  Starting Servlet engine: [Apache Tomcat/10.1.17]
2024-10-15 13:52:28.307 [Launch VThread] [DirectJDKLog.java:173] INFO  Initializing Spring embedded WebApplicationContext
2024-10-15 13:52:28.309 [Launch VThread] [ServletWebServerApplicationContext.java:296] INFO  Root WebApplicationContext: initialization completed in 1074 ms
2024-10-15 13:52:28.343 [Launch VThread] [ConfigurationConfig.kt:47] INFO  已创建脚本配置文件，路径：C:\Users\akane\Desktop\sc\.\config\script.properties
2024-10-15 13:52:28.875 [Launch VThread] [DirectJDKLog.java:173] INFO  Starting ProtocolHandler ["http-nio-8848"]
2024-10-15 13:52:28.896 [Launch VThread] [TomcatWebServer.java:241] INFO  Tomcat started on port 8848 (http) with context path ''
2024-10-15 13:52:28.905 [Launch VThread] [StartupInfoLogger.java:56] INFO  Started application in 2.295 seconds (process running for 2.978)
2024-10-15 13:52:28.913 [ExtraPool Thread-0] [AbstractInitializer.java:18] INFO  执行PluginInitializer
2024-10-15 13:52:28.926 [ExtraPool Thread-0] [PluginManager.kt:180] INFO  加载CardPlugin: 【name: 基础, version: 1.0.0, author: XiaoJiawei, id: xjw-base-plugin, description: 捆绑】
2024-10-15 13:52:28.928 [ExtraPool Thread-0] [CardActionManager.kt:39] INFO  重新加载卡牌库
2024-10-15 13:52:28.936 [ExtraPool Thread-0] [PluginManager.kt:180] INFO  加载DeckPlugin: 【name: 基础, version: 1.0.0, author: XiaoJiawei, id: xjw-base-plugin, description: 捆绑，通用策略，未对卡牌和卡组适配，自行组一套无战吼无法术的套牌即可】
2024-10-15 13:52:28.938 [ExtraPool Thread-0] [DeckStrategyManager.kt:106] INFO  重新加载套牌库
2024-10-15 13:52:28.938 [ExtraPool Thread-0] [AbstractInitializer.java:18] INFO  执行ResourceInitializer
2024-10-15 13:52:28.939 [ExtraPool Thread-0] [ResourceInitializer.java:42] INFO  资源文件复制成功
2024-10-15 13:52:28.940 [ExtraPool Thread-0] [AbstractInitializer.java:18] INFO  执行PathInitializer
2024-10-15 13:52:28.940 [ExtraPool Thread-0] [PathInitializer.java:37] INFO  未配置战网安装路径，尝试从注册表读取
2024-10-15 13:52:28.987 [ExtraPool Thread-0] [PathInitializer.java:39] INFO  从注册表读取到战网安装路径
2024-10-15 13:52:28.990 [ExtraPool Thread-0] [PathInitializer.java:50] INFO  未配置炉石传说安装路径，尝试从注册表读取
2024-10-15 13:52:28.990 [ExtraPool Thread-0] [PathInitializer.java:52] INFO  从注册表读取到炉石传说安装路径
2024-10-15 13:52:28.991 [ExtraPool Thread-0] [AbstractInitializer.java:18] INFO  执行LogInitializer
2024-10-15 13:52:28.992 [ExtraPool Thread-0] [LogInitializer.java:56] INFO  log.config文件重写完成，游戏日志已打开，首次重写需要重启炉石传说
2024-10-15 13:52:29.007 [ExtraPool Thread-0] [AbstractInitializer.java:18] INFO  执行WebInitializer
2024-10-15 13:52:29.007 [ExtraPool Thread-0] [WebInitializer.java:33] INFO  自动打开Web界面开关处于关闭状态
2024-10-15 13:52:29.403 [SchedulePool Thread-2] [VersionListener.java:81] INFO  开始从Gitee检查更新
2024-10-15 13:52:29.404 [SchedulePool Thread-2] [VersionListener.java:82] INFO  更新dev：false
2024-10-15 13:52:30.244 [SchedulePool Thread-2] [VersionListener.java:127] INFO  已是最新，当前版本：Release{tagName='v4.0.0.3-PATCH', preRelease=true, name='null', body='null'}, 最新版本：Release{tagName='v4.0.0.3-PATCH', preRelease=false, name='hs-script_v4.0.0.3-PATCH', body='
#### v4.0.0.3-PATCH

- 修复基础策略下我方满场依旧尝试上怪的问题
'}
2024-10-15 13:52:37.392 [JavaFX Application Thread] [DeckStrategyManager.kt:71] INFO  挂机卡组改为: 基础策略，模式: 标准模式
2024-10-15 13:53:01.707 [JavaFX Application Thread] [PauseConfig.java:58] INFO  当前处于运行状态
2024-10-15 13:53:01.707 [CorePool Thread-0] [Core.java:54] INFO  热键：Ctrl+P 开始/停止程序,Alt+P 关闭程序
2024-10-15 13:53:01.708 [CorePool Thread-0] [AbstractStarter.java:18] INFO  执行ClearStarter
2024-10-15 13:53:01.708 [CorePool Thread-0] [SystemUtil.java:118] INFO  终止所有监听器
2024-10-15 13:53:01.708 [CorePool Thread-0] [SystemUtil.java:126] INFO  终止所有额外线程
2024-10-15 13:53:01.709 [CorePool Thread-0] [SystemUtil.java:110] INFO  终止所有模式任务
2024-10-15 13:53:01.709 [CorePool Thread-0] [SystemUtil.java:133] INFO  终止所有程序启动定时器
2024-10-15 13:53:02.711 [CorePool Thread-0] [Mode.java:37] INFO  已重置模式状态
2024-10-15 13:53:02.711 [CorePool Thread-0] [AbstractStarter.java:18] INFO  执行PlatformStarter
2024-10-15 13:53:02.886 [CorePool Thread-0] [AbstractStarter.java:18] INFO  执行LoginPlatformStarter
2024-10-15 13:53:03.051 [CorePool Thread-0] [AbstractStarter.java:18] INFO  执行GameStarter
2024-10-15 13:53:03.051 [CorePool Thread-0] [GameStarter.java:45] INFO  开始检查炉石传说
2024-10-15 13:53:03.189 [CorePool Thread-0] [GameStarter.java:95] INFO  炉石传说正在运行
2024-10-15 13:53:04.194 [ExtraPool Thread-0] [AbstractStarter.java:18] INFO  执行InjectStarter
```
原本是能用的，在一次暂停之后就在没成功过，一直在主界面没有进入选牌模式，按照前面issue提示的安装[64位Visual C++ 重启电脑也没有用

**Comment by xjw580** [comment]
用[v4.0.2-BETA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.2-BETA)看看

**Comment by zwsts** [comment]
> 用[v4.0.2-BETA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.2-BETA)看看
大佬，我用这个beta版试了下还是有错，日志如下
```
2024-10-15 15:20:11.621 [ExtraPool Thread-0] [GlobalHotkeyListener.kt:41] INFO  开始/暂停热键：Ctrl+P
2024-10-15 15:20:11.622 [ExtraPool Thread-0] [VersionListener.kt:100] INFO  版本更新检测已启动
2024-10-15 15:20:11.623 [ExtraPool Thread-0] [WorkListener.kt:36] INFO  工作时段监听已启动
2024-10-15 15:20:12.123 [ExtraPool Thread-1] [VersionListener.kt:205] INFO  开始检查更新，更新开发版：false
2024-10-15 15:20:12.912 [ExtraPool Thread-1] [VersionListener.kt:227] INFO  已是最新，当前版本：【v4.0.2-BETA】, 最新版本：【v4.0.0.3-PATCH】
2024-10-15 15:20:20.933 [JavaFX Application Thread] [DeckStrategyManager.kt:47] INFO  挂机策略改为: 秒投策略，模式: 标准模式
2024-10-15 15:20:23.015 [ExtraPool Thread-2] [Core.kt:44] INFO  当前处于【运行】状态
2024-10-15 15:20:23.019 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【ClearStarter】
2024-10-15 15:20:23.019 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【PlatformStarter】
2024-10-15 15:20:23.255 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【LoginPlatformStarter】
2024-10-15 15:20:23.452 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【GameStarter】
2024-10-15 15:20:23.452 [CorePool Thread-0] [GameStarter.kt:33] INFO  开始检查炉石传说
2024-10-15 15:20:23.585 [CorePool Thread-0] [GameStarter.kt:87] INFO  炉石传说正在运行
2024-10-15 15:20:23.589 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【InjectStarter】
2024-10-15 15:20:23.590 [CorePool Thread-0] [LogRunnable.java:23] ERROR Runnable发生错误
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at club.xiaojiawei.hsscript.starter.InjectStarter.execStart(InjectStarter.kt:35)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.GameStarter.next(GameStarter.kt:102)
	at club.xiaojiawei.hsscript.starter.GameStarter.execStart(GameStarter.kt:34)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.LoginPlatformStarter.execStart(LoginPlatformStarter.kt:28)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.PlatformStarter.execStart(PlatformStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.ClearStarter.execStart(ClearStarter.kt:16)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.core.Core.start$lambda$8(Core.kt:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at club.xiaojiawei.bean.LogRunnable.run(LogRunnable.java:21)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by xjw580** [comment]
> > 用[v4.0.2-BETA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.2-BETA)看看
> 
> 大佬，我用这个beta版试了下还是有错，日志如下
> 
> ```
> 2024-10-15 15:20:11.621 [ExtraPool Thread-0] [GlobalHotkeyListener.kt:41] INFO  开始/暂停热键：Ctrl+P
> 2024-10-15 15:20:11.622 [ExtraPool Thread-0] [VersionListener.kt:100] INFO  版本更新检测已启动
> 2024-10-15 15:20:11.623 [ExtraPool Thread-0] [WorkListener.kt:36] INFO  工作时段监听已启动
> 2024-10-15 15:20:12.123 [ExtraPool Thread-1] [VersionListener.kt:205] INFO  开始检查更新，更新开发版：false
> 2024-10-15 15:20:12.912 [ExtraPool Thread-1] [VersionListener.kt:227] INFO  已是最新，当前版本：【v4.0.2-BETA】, 最新版本：【v4.0.0.3-PATCH】
> 2024-10-15 15:20:20.933 [JavaFX Application Thread] [DeckStrategyManager.kt:47] INFO  挂机策略改为: 秒投策略，模式: 标准模式
> 2024-10-15 15:20:23.015 [ExtraPool Thread-2] [Core.kt:44] INFO  当前处于【运行】状态
> 2024-10-15 15:20:23.019 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【ClearStarter】
> 2024-10-15 15:20:23.019 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【PlatformStarter】
> 2024-10-15 15:20:23.255 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【LoginPlatformStarter】
> 2024-10-15 15:20:23.452 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【GameStarter】
> 2024-10-15 15:20:23.452 [CorePool Thread-0] [GameStarter.kt:33] INFO  开始检查炉石传说
> 2024-10-15 15:20:23.585 [CorePool Thread-0] [GameStarter.kt:87] INFO  炉石传说正在运行
> 2024-10-15 15:20:23.589 [CorePool Thread-0] [AbstractStarter.kt:18] INFO  执行【InjectStarter】
> 2024-10-15 15:20:23.590 [CorePool Thread-0] [LogRunnable.java:23] ERROR Runnable发生错误
> java.lang.NullPointerException: null
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
> 	at club.xiaojiawei.hsscript.starter.InjectStarter.execStart(InjectStarter.kt:35)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
> 	at club.xiaojiawei.hsscript.starter.GameStarter.next(GameStarter.kt:102)
> 	at club.xiaojiawei.hsscript.starter.GameStarter.execStart(GameStarter.kt:34)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
> 	at club.xiaojiawei.hsscript.starter.LoginPlatformStarter.execStart(LoginPlatformStarter.kt:28)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
> 	at club.xiaojiawei.hsscript.starter.PlatformStarter.execStart(PlatformStarter.kt:20)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
> 	at club.xiaojiawei.hsscript.starter.ClearStarter.execStart(ClearStarter.kt:16)
> 	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
> 	at club.xiaojiawei.hsscript.core.Core.start$lambda$8(Core.kt:66)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at club.xiaojiawei.bean.LogRunnable.run(LogRunnable.java:21)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> ```

你软件根目录有injectUtil.exe这个文件吗？lib/dll目录有libHS.dll文件吗？

**Comment by zwsts** [comment]
> 你软件根目录有injectUtil.exe这个文件吗？lib/dll目录有libHS.dll文件吗？

根目录没有injectUtil.exe，每次重新加进去再运行程序会被删掉，lib/dll目录有libHS.dll文件

**Comment by xjw580** [comment]
> > 你软件根目录有injectUtil.exe这个文件吗？lib/dll目录有libHS.dll文件吗？
> 
> 根目录没有injectUtil.exe，每次重新加进去再运行程序这个文件都会被删掉，lib/dll目录有libHS.dll文件

是不是被杀毒软件删了👽

**Comment by zwsts** [comment]
> 是不是被杀毒软件删了👽

已解决，winddows自带的杀毒软件删掉了injectUtil.exe
关掉就行了
<img width="282" alt="image" src="https://github.com/user-attachments/assets/e9f44364-3ec8-40c3-bc7a-9373dcdb9652">
