### ISSUE TITLE
Runnable 发生异常 NunPointException 这个是啥问题呀大佬 我在之前的issues 中没有发现相关的解释

### ISSUE THREAD

**Issue by shunkanghe** [xjw580/Hearthstone-Script#56]
24-10-20 21:18:53.701 [CorePool Thread-1] [AbstractStarter.kt:18] INFO  执行【LoginPlatformStarter】
2024-10-20 21:18:53.853 [CorePool Thread-1] [AbstractStarter.kt:18] INFO  执行【GameStarter】
2024-10-20 21:18:53.853 [CorePool Thread-1] [GameStarter.kt:33] INFO  开始检查炉石传说
2024-10-20 21:18:53.854 [CorePool Thread-1] [GameStarter.kt:87] INFO  炉石传说正在运行
2024-10-20 21:18:53.854 [CorePool Thread-1] [AbstractStarter.kt:18] INFO  执行【InjectStarter】
2024-10-20 21:18:53.854 [CorePool Thread-1] [LogRunnable.java:23] ERROR Runnable发生错误
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at club.xiaojiawei.hsscript.starter.InjectStarter.execStart(InjectStarter.kt:42)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.GameStarter.next(GameStarter.kt:102)
	at club.xiaojiawei.hsscript.starter.GameStarter.execStart(GameStarter.kt:34)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.LoginPlatformStarter.execStart(LoginPlatformStarter.kt:28)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.PlatformStarter.execStart(PlatformStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:44)
	at club.xiaojiawei.hsscript.starter.ClearStarter.execStart(ClearStarter.kt:16)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:20)
	at club.xiaojiawei.hsscript.core.Core.start$lambda$8(Core.kt:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at club.xiaojiawei.bean.LogRunnable.run(LogRunnable.java:21)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xjw580** [comment]
翻issue

**Comment by xjw580** [comment]
#40
