### ISSUE TITLE
Runnable发生错误，查看脚本日志获取详细错误信息

### ISSUE THREAD

**Issue by z5424379** [xjw580/Hearthstone-Script#76]
2024-11-06 22:14:06.440 [JavaFX Application Thread] [VersionListener.kt:205] INFO  开始检查更新，更新开发版：false
2024-11-06 22:14:06.778 [JavaFX Application Thread] [VersionListener.kt:227] INFO  已是最新，当前版本：【v4.1.0-GA】, 最新版本：【v4.1.0-GA】
2024-11-06 22:14:28.810 [ExtraPool Thread-3] [Core.kt:46] INFO  当前处于【运行】状态
2024-11-06 22:14:28.810 [CorePool Thread-3] [AbstractStarter.kt:24] INFO  执行【ClearStarter】
2024-11-06 22:14:28.810 [CorePool Thread-3] [AbstractStarter.kt:24] INFO  执行【PlatformStarter】
2024-11-06 22:14:28.925 [CorePool Thread-3] [AbstractStarter.kt:24] INFO  执行【LoginPlatformStarter】
2024-11-06 22:14:29.038 [CorePool Thread-3] [AbstractStarter.kt:24] INFO  执行【GameStarter】
2024-11-06 22:14:29.039 [CorePool Thread-3] [GameStarter.kt:34] INFO  开始检查炉石传说
2024-11-06 22:14:29.042 [CorePool Thread-3] [GameStarter.kt:84] INFO  炉石传说正在运行
2024-11-06 22:14:29.043 [CorePool Thread-3] [AbstractStarter.kt:24] INFO  执行【InjectStarter】
2024-11-06 22:14:29.043 [CorePool Thread-3] [LogRunnable.java:23] ERROR Runnable发生错误
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at club.xiaojiawei.hsscript.starter.InjectStarter.execStart(InjectStarter.kt:42)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:26)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:50)
	at club.xiaojiawei.hsscript.starter.GameStarter.next(GameStarter.kt:99)
	at club.xiaojiawei.hsscript.starter.GameStarter.execStart(GameStarter.kt:35)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:26)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:50)
	at club.xiaojiawei.hsscript.starter.LoginPlatformStarter.execStart(LoginPlatformStarter.kt:27)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:26)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:50)
	at club.xiaojiawei.hsscript.starter.PlatformStarter.execStart(PlatformStarter.kt:19)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:26)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.startNextStarter(AbstractStarter.kt:50)
	at club.xiaojiawei.hsscript.starter.ClearStarter.execStart(ClearStarter.kt:16)
	at club.xiaojiawei.hsscript.starter.AbstractStarter.start(AbstractStarter.kt:26)
	at club.xiaojiawei.hsscript.core.Core.start$lambda$9(Core.kt:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at club.xiaojiawei.bean.LogRunnable.run(LogRunnable.java:21)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xjw580** [comment]
https://github.com/xjw580/Hearthstone-Script/blob/master/QUESTION.md

**Comment by z5424379** [comment]
> [QUESTION](https://github.com/xjw580/Hearthstone-Script/blob/master/QUESTION.md)

管理员运行了，库也安装了，电脑没有装杀毒软件。然后那个mvn，下载的zip的话，没有pom.xml

**Comment by z5424379** [comment]
#40 找到问题了

**Comment by xjw580** [comment]
你软件根目录下的injectUtil.exe文件呢？
