### ISSUE TITLE
无法启动script的基础性错误

### ISSUE THREAD

**Issue by robot-2233** [xjw580/Hearthstone-Script#91]
force-stop.exe后无法启动脚本

**Comment by robot-2233** [comment]
log部分如下：

2024-11-15 09:04:49.531 [ExtraPool Thread-5] [Core.kt:39] INFO  当前处于【停止】状态
2024-11-15 09:04:56.334 [Launch VThread] [AbstractInitializer.kt:15] INFO  执行【BaseInitializer】
2024-11-15 09:04:56.840 [Launch VThread] [ConfigUtil.kt:42] INFO  配置文件读取完毕：E:\lscs\script-dev\config\script.ini
2024-11-15 09:04:56.841 [Launch VThread] [AbstractInitializer.kt:15] INFO  执行【ResourceInitializer】
2024-11-15 09:04:56.841 [Launch VThread] [AbstractInitializer.kt:15] INFO  执行【GamePathInitializer】
2024-11-15 09:04:57.014 [Launch VThread] [AbstractInitializer.kt:15] INFO  执行【GameLogInitializer】
2024-11-15 09:04:57.017 [Launch VThread] [AbstractInitializer.kt:15] INFO  执行【PluginInitializer】
2024-11-15 09:04:57.034 [Launch VThread] [PluginManager.kt:173] INFO  加载CardPlugin：{name: 基础, version: 1.0.0, author: XiaoJiawei, id: xjw-base-plugin, description: 捆绑}
2024-11-15 09:04:57.035 [Launch VThread] [CardActionManager.kt:48] INFO  重新加载卡牌库
2024-11-15 09:04:57.044 [Launch VThread] [PluginManager.kt:173] INFO  加载DeckPlugin：{name: 基础, version: 1.0.0, author: XiaoJiawei, id: xjw-base-plugin, description: 捆绑。包含以下策略
秒投策略：开局秒投。
基础策略：未对卡牌和卡组适配，自行组一套无战吼无法术的套牌即可。
激进策略：会在基础策略的基础上使用战吼，法术，地标牌（依旧不识别战吼或法术）。}
2024-11-15 09:04:57.045 [Launch VThread] [DeckStrategyManager.kt:80] INFO  重新加载套牌库
2024-11-15 09:04:57.963 [ExtraPool Thread-0] [GlobalHotkeyListener.kt:37] INFO  退出热键：Alt+P
2024-11-15 09:04:57.964 [ExtraPool Thread-0] [GlobalHotkeyListener.kt:44] INFO  开始/暂停热键：Ctrl+P
2024-11-15 09:04:57.965 [ExtraPool Thread-0] [VersionListener.kt:100] INFO  版本更新检测已启动
2024-11-15 09:04:57.966 [ExtraPool Thread-0] [WorkListener.kt:35] INFO  工作时段监听已启动
2024-11-15 09:04:57.979 [ExtraPool Thread-0] [MainApplication.kt:162] INFO  检测到多台显示器，开始运行后炉石传说不要移动到其他显示器
2024-11-15 09:04:58.467 [ExtraPool Thread-1] [VersionListener.kt:205] INFO  开始检查更新，更新开发版：false
2024-11-15 09:04:59.164 [ExtraPool Thread-1] [VersionListener.kt:227] INFO  已是最新，当前版本：【v4.1.0-GA】, 最新版本：【v4.1.0-GA】
2024-11-15 09:05:01.033 [ExtraPool Thread-3] [Core.kt:46] INFO  当前处于【运行】状态
2024-11-15 09:05:01.036 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【ClearStarter】
2024-11-15 09:05:01.037 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【PlatformStarter】
2024-11-15 09:05:01.274 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【LoginPlatformStarter】
2024-11-15 09:05:01.452 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【GameStarter】
2024-11-15 09:05:01.453 [CorePool Thread-0] [GameStarter.kt:34] INFO  开始检查炉石传说
2024-11-15 09:05:01.462 [CorePool Thread-0] [GameStarter.kt:84] INFO  炉石传说正在运行
2024-11-15 09:05:01.632 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【InjectStarter】
2024-11-15 09:05:01.664 [CorePool Thread-0] [InjectStarter.kt:66] INFO  注入dll成功
2024-11-15 09:05:01.664 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【LogListenStarter】
2024-11-15 09:05:01.667 [CorePool Thread-0] [LogListenStarter.kt:19] INFO  游戏日志目录读取成功：E:\lscs\lscs\Hearthstone\Logs\Hearthstone_2024_11_15_05_23_14
2024-11-15 09:05:01.668 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【ExceptionListenStarter】
2024-11-15 09:05:01.668 [CorePool Thread-0] [ExceptionListenStarter.kt:42] INFO  开始监听异常情况
2024-11-15 09:05:01.673 [CorePool VThread-0] [AbstractLogListener.kt:69] INFO  开始监听日志【Decks.log】
2024-11-15 09:05:01.694 [CorePool VThread-0] [AbstractLogListener.kt:69] INFO  开始监听日志【Power.log】
2024-11-15 09:05:01.700 [CorePool VThread-0] [WarEx.kt:105] INFO  已重置游戏状态
2024-11-15 09:05:01.701 [CorePool VThread-0] [AbstractLogListener.kt:69] INFO  开始监听日志【LoadingScreen.log】
2024-11-15 09:05:01.995 [CorePool VThread-0] [AbstractLogListener.kt:74] ERROR kotlin.Unit
java.lang.IllegalArgumentException: No enum constant club.xiaojiawei.enums.ModeEnum.BACON_COLLECTION
	at java.base/java.lang.Enum.valueOf(Enum.java:293)
	at club.xiaojiawei.enums.ModeEnum.valueOf(ModeEnum.kt)
	at club.xiaojiawei.hsscript.listener.log.ScreenLogListener.dealOldLog(ScreenLogListener.kt:27)
	at club.xiaojiawei.hsscript.listener.log.AbstractLogListener.listen(AbstractLogListener.kt:72)
	at club.xiaojiawei.hsscript.listener.log.AbstractLogListener.listenNextListener(AbstractLogListener.kt:51)
	at club.xiaojiawei.hsscript.listener.log.AbstractLogListener.listen(AbstractLogListener.kt:90)
	at club.xiaojiawei.hsscript.listener.log.AbstractLogListener.listenNextListener(AbstractLogListener.kt:51)
	at club.xiaojiawei.hsscript.listener.log.AbstractLogListener.listen(AbstractLogListener.kt:90)
	at club.xiaojiawei.hsscript.starter.LogListenStarter.execStart$lambda$2$lambda$1(LogListenStarter.kt:21)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
2024-11-15 09:05:36.838 [ExtraPool Thread-2] [Core.kt:39] INFO  当前处于【停止】状态

**Comment by xjw580** [comment]
看日志你这报错是进入了未适配的模式BACON_COLLECTION

**Comment by xjw580** [comment]
执行force-stop.exe只会杀死软件进程，并不会导致软件无法启动

**Comment by robot-2233** [comment]
那该怎么修复这个情况
我目前关闭程序后打开依然报错

**Comment by xjw580** [comment]
> 那该怎么修复这个情况 我目前关闭程序后打开依然报错

重启游戏

**Comment by robot-2233** [comment]
是的是的 关闭游戏，从关闭状态开始运行就好了
