### ISSUE TITLE
InterruptedException报错及出牌权重问题

### ISSUE THREAD

**Issue by llsccm** [xjw580/Hearthstone-Script#94]
版本: v4.1.3-BETA

```
2024-11-15 23:17:45.547 [ListenLogPool Thread-1] [WarEx.kt:181] INFO  本局游戏投降者：
2024-11-15 23:17:45.547 [ListenLogPool Thread-1] [WarEx.kt:144] INFO  本局游戏时长：7分钟
2024-11-15 23:17:45.548 [ListenLogPool Thread-1] [WarEx.kt:167] INFO  本局游戏获得经验值：42
2024-11-15 23:17:45.548 [ListenLogPool Thread-1] [MainController.java:281] INFO  已完成第 1 把游戏
2024-11-15 23:17:45.629 [OutCard Thread] [LogRunnable.java:23] ERROR Runnable发生错误
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep0(Native Method)
	at java.base/java.lang.Thread.sleep(Thread.java:509)
	at club.xiaojiawei.CardAction.delay(CardAction.kt:125)
	at club.xiaojiawei.CardAction.delay$default(CardAction.kt:123)
	at club.xiaojiawei.CardAction.attack(CardAction.kt:82)
	at club.xiaojiawei.CardAction.attack$default(CardAction.kt:73)
	at club.xiaojiawei.util.DeckStrategyUtil.attack$lambda$28(DeckStrategyUtil.kt:493)
	at club.xiaojiawei.util.DeckStrategyUtil$Result.execAction(DeckStrategyUtil.kt:79)
	at club.xiaojiawei.util.DeckStrategyUtil.clean(DeckStrategyUtil.kt:275)
	at club.xiaojiawei.util.DeckStrategyUtil.cleanPlay(DeckStrategyUtil.kt:564)
	at club.xiaojiawei.util.DeckStrategyUtil.cleanPlay$default(DeckStrategyUtil.kt:559)
	at club.xiaojiawei.HsCommonDeckStrategy.executeOutCard(HsCommonDeckStrategy.kt:43)
	at club.xiaojiawei.HsRadicalDeckStrategy.executeOutCard(HsRadicalDeckStrategy.kt:86)
	at club.xiaojiawei.hsscript.strategy.DeckStrategyActuator.outCard(DeckStrategyActuator.kt:130)
	at club.xiaojiawei.hsscript.strategy.phase.GameTurnPhaseStrategy.dealTagChangeThenIsOver$lambda$1(GameTurnPhaseStrategy.kt:31)
	at club.xiaojiawei.bean.LogRunnable.run(LogRunnable.java:21)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-15 23:17:46.550 [ListenLogPool Thread-1] [GameUtil.kt:366] INFO  点掉游戏结束结算页面
```

现在会识别水晶，打出术士的捣蛋鬼影响水晶会导致策略中止。

还有一个权重问题，在2水晶回合中，一个权重1.1的一费随从和一个1.0的二费随从，哪一个会优先打出？观测的结果是常常打出一费随从。

**Comment by xjw580** [comment]
> InterruptedException

如果只是InterruptedException报错，不用管

**Comment by xjw580** [comment]
[v4.1.4-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.1.4-DEV)已优化出牌权重问题
